spring.application.name=aattral_demo_project
modbus.host=127.0.0.1
modbus.port=1502

modbus.slaves.temperature=1
modbus.slaves.pressure=2
modbus.slaves.relay=3

spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:mysql://localhost:3306/aattral
spring.datasource.username=root
spring.datasource.password=Abishek@123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql: true